export const categories = [
  [
    'Boys Names',
    'Canadian Cities',
    'Things That Are Cold',
    'Things You Don\'t Want In The House',
    'Pro Sports Teams',
    'Insects',
    'Things In A Coffee Bar',
    'Things You Mix Up',
    'TV Shows',
    'Things Found In The Ocean',
    'Kinds Of Weather',
    'Foods That Kids Hate',
  ],
  [
    'Famous Females',
    'Medicine/Drugs',
    'Machines',
    'Hobbies',
    'Acronyms (eg. NASA)',
    'Things You Plug In',
    'Animals',
    'Languages',
    'Things You Grab On The Way Out The Door',
    'Junk Food',
    'Things That Grow',
    'Things In An Arcade',
  ],
  [
    'Articles Of Clothing',
    'Desserts',
    'Car Parts',
    'Things At A Gas Station',
    'Athletes',
    '4-Letter Words',
    'Things You Fold',
    'Things In A Junk Drawer',
    'Things You Do Online',
    'Things At The Beach',
    'Things You Dream About',
    'Tools',
  ],
  [
    'Heroes',
    'Gifts/Presents',
    'Terms Of Endearment',
    'Kinds Of Dances',
    'Things That Are Black',
    'Vehicles',
    'Things Found In An Arena',
    'Things People Gossip About',
    'Colors',
    'Things In A Souvenir Shop',
    'Items In Your Purse/Wallet',
    'World Records',
  ],
  [
    'Sandwiches',
    'Things You Can Do With Your Feet',
    'World Leaders/Politicians',
    'School Subjects',
    'Excuses For Being Late',
    'Ice Cream Flavors',
    'Things With Balls',
    'Television Stars',
    'Things In A Park',
    'Foreign Cities',
    'Stones/Gems',
    'Musical Instruments',
  ],
  [
    'Nicknames',
    'Things In The Sky',
    'Things With Windows',
    'Colleges/Universities',
    'Fish',
    'Countries',
    'Things That Have Spots',
    'Things That Smell Bad',
    'Things You\'re Afraid Of',
    'Terms Of Measurement',
    'Items In This Room',
    'Book Titles',
  ],
  [
    'Fictional Characters',
    'Places To Go On A Date',
    'Magazines',
    'Capitals',
    'Kinds Of Candy',
    'Things YOu Save Up To Buy',
    'Footwear',
    'Something You Keep Hidden',
    'Items In A Suitcase',
    'Things With Tails',
    'Sports Equipment',
    'Crimes',
  ],
  [
    'Things That Are Sticky',
    'Awards/Ceremonies',
    'Cars',
    'Spices/Herbs',
    'Bad Habits',
    'Cosmetics/Toiletries',
    'Celebrities',
    'Things To Do With Leftover Turkey',
    'Reptiles/Amphibians',
    'Fads',
    'Leisure Activities',
    'Things You Are Allergic To',
  ],
  [
    'Restaurants',
    'Notorious People',
    'Fruits',
    'Weapons',
    'Toys',
    'Household Chores',
    'Bodies Of Water',
    'Authors',
    'Halloween Costumes',
    'Funny Movies',
    'Things That Are Round',
    'Things In A Pet Store',
  ],
  [
    'Sports',
    'Song Titles',
    'Parts Of The Body',
    'Ethnic Foods',
    'Things You Shout',
    'Birds',
    'Girls Names',
    'Ways To Get From Here To There',
    'Cooking Terms',
    'Villians/Monsters',
    'Flowers',
    'Things That Weigh Less Than One Kilo',
  ],
  [
    'Things That Need To Be Cleaned',
    'Famous Duos And Trios',
    'Things Found In A Desk',
    'Vacation Spots',
    'Things At A Hospital',
    'Words Associated With Money',
    'Items In A Vending Machine',
    'Movie Titles',
    'Games',
    'Things That You Wear',
    'Beers',
    'Things At A Circus',
  ],
  [
    'Vegetables',
    'States',
    'Things You Throw Away',
    'Occupations',
    'Foods You Eat On Holidays',
    'Cartoon Characters',
    'Types Of Drink',
    'Musical Groups',
    'Science Things',
    'Things To Do On A Rainy Day',
    'Trees',
    'Personality Traits',
  ],
  [
    'Things You Can Tie In A Knot',
    'Things That Are Soft',
    'Things In A Sci-Fi Movie',
    'Words With Four Different Vowels',
    'Things That Kids Play With',
    'Things At A Wedding',
    'Hot Places',
    'Things In Outer Space',
    'Sounds',
    'Things At A Diner',
    'Famous Singers',
    'Things At An Amusement Park',
  ],
  [
    'Worn Above The Waist',
    'Things That Are Bright',
    'Things That Have Numbers',
    'Found In A Gym/Health Club',
    'Chain Stores',
    'Ways To Say Hi And Bye',
    'Things In The Backyard',
    'Things People Use To Decorate Their Houses',
    'Items In An Office',
    'Things In Pairs Or Sets',
    'Artists',
    'Things In Las Vegas',
  ],
  [
    'Things At A Zoo',
    'Things Smaller Than Your Fist',
    'Things That Can Fly',
    'Things You Eat On A Diet',
    'Words Ending In "LY"',
    'Things Found Under The Table',
    'Things In A Hotel',
    'Things You Can Do In 5 Minutes Or Less',
    'Things With Claws',
    'Party Things',
    'Reasons To Skip School/Work',
    'Titles People Have',
  ],
  [
    'Things That Go Well With Chocolate',
    'Things In A Mystery Novel',
    'Websites',
    'Loud Things',
    'Things You Eat With A Spoon',
    'Famous Sayings',
    'Underground Things',
    'Things In The Wild West',
    'Things In An Airport',
    'Words With Double Letters',
    'Found In New York City',
    'Things In Fairy Tales',
  ],
];